### ISSUE TITLE
Color schema for signup page

### ISSUE THREAD

**Issue by vcellmike** [pepe454/CompModelMatch#12]
Pink font over orange background is invisible, e.g. "There are currently no users defined in the system. You should now register an initial user. This initial user will become the Administrator of the system."

**Comment by vcellmike** [comment]
![Screen Shot 2020-05-27 at 10 01 05 AM](https://user-images.githubusercontent.com/29076280/83029780-0fe07080-a001-11ea-889a-782eca290d90.png)

**Comment by sjha2048** [comment]
![Screenshot from 2020-06-02 13-59-21](https://user-images.githubusercontent.com/30971724/83499159-863a1280-a4da-11ea-9017-bfa42d3dca49.png)
I have changed the text color
